### ISSUE TITLE
The code is not compiling properly.

### ISSUE THREAD

**Issue by jbjares** [phasapis/sfmmain#1]
Hi All,
Please, I would like to know why the code committed by Panos is not compiling properly. However, the same code committed by me on the SIFEM insight-centre private repository is compiling properly.

Code on the SIFEM old private repository:
![image](https://cloud.githubusercontent.com/assets/1163531/12322524/b5fd02d8-baac-11e5-8c0d-a451cc4f7946.png)

Code on the SIFEM new public repository:
![image](https://cloud.githubusercontent.com/assets/1163531/12322377/9abb4170-baab-11e5-9c62-de22f0bda631.png)

Thanks in advance.

**Comment by phasapis** [comment]
It must be an issue with Eclipse. It compiles perfectly with Netbeans 8.0.2 - attached scrrenshot
![screen](https://cloud.githubusercontent.com/assets/1092252/12323214/3e07746e-bac2-11e5-98f1-0241a8600413.png)

**Comment by jbjares** [comment]
Thanks. I'm waiting for the commit of new changes as did you mentioned in our earlier chat. 

Thanks in advance :)
